language: ruby
bundler_args: --without development
rvm:
  - "2.0.0"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JS=true
    - CONTINUOUS_INTEGRATION=true
before_install:
  - sudo apt-get update
  - sudo apt-get install libclamav-dev
  - sudo bash -c 'echo Eicar-Test-Signature:0:0:58354f2150254041505b345c505a58353428505e2937434329377d2445494341522d5354414e444152442d414e544956495255532d544553542d46494c452124482b482a > /var/lib/clamav/test.ndb'
  - export PATH="$PATH:$(pwd)/fits"
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/redis.yml.sample config/redis.yml"
  - "cp config/devise.yml.sample config/devise.yml"
  - "cp config/solr.yml.sample config/solr.yml"
  - "cp config/fedora.yml.sample config/fedora.yml"
  - "cp config/hydra-ldap.yml.sample config/hydra-ldap.yml"
  - "bundle exec rails g hydra:jetty"
services:
  - redis-server
script:
  - "bundle exec rake scholarsphere:ci"
notifications:
  email:
    recipients:
      - "ul-dlt-hydra@lists.psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
